spring:
  profiles:
    active: rabbitMQ
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
server:
  port: 8080
configuration:
  broker:
    exchangesInsertion: x.management
    routing-key-insertion: management
    queue-insertion: q.management.insert
    exchanges-retrieve: x.management.get
    routing-key-retrieve: management.get
    queue-retrieve: q.management.get
    hostname: localhost
    port: 5672
    username: admin
    password: admin
security:
  user:
    name: act
    password: act
management:
  security:
    enabled: true
    roles: ACTRADMIN
  context-path: /manage
